title: ALEX SWANDI
description: MAHASISWA SISTEM INFORMASI UIN SUSKA RIAU

url: http://brianmaierjr.github.com/long-haul
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5
background:         'uin suska riau.png'

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: sif.uin-suska
   url: http://sif.uin-suska.ac.id/

social:
   github: brianmaierjr
   twitter: brianmaierjr
   facebook: brianmaierjr
   email: blade.alexswandi@gmail.com

google_analytics: "UA-58263416-1"
